### ISSUE TITLE
Timeout in simulation

### ISSUE THREAD

**Issue by olofk** [onchipuis/mriscvcore#2]
I'm working on packaging mriscv for FuseSoC, but I haven't been able to complete any simulations yet. Running with the default firmware I just get lines saying `7..OK` over and over again until the simulations times out

**Comment by olofk** [comment]
That comment was for the mriscvcore_tb, but actually, I can't get any of the testbenches working.
sim_IRQf (in IRQ_tb) doesn't do anything, MULT_tb doesn't work because `funct3` isn't defined on the UUT and both sim1 (in ALU_tb) and Sim_DecInstru1 (in DECO_INSTR_tb.v) also tries to use ports that doesn't exist on the UUT

**Comment by onchipuis** [comment]
Fixed in https://github.com/onchipuis/mriscvcore/commit/6ac262b776bf23ceadd42651092a762891b7fdfa
Added an "OK" detector.
About the other testbenches, they will be corrected because they were used for the previous implementations of each block. But we use the RISC-V tests for testing each implemented instruction.
Thanks for reporting.
